from tkinter import *
root=Tk()
root.geometry("733x566")
root.title("pycharm")
def myfunc():
    print("Iam not at all discent")
filemenu=Menu(root)
m1=Menu(filemenu)
m1.add_command(label="New project",command=myfunc)
m1.add_command(label="Save",command=myfunc)
m1.add_separator()
m1.add_command(label="Save As",command=myfunc)
m1.add_command(label="Print",command=myfunc)
root.config(menu=filemenu)
filemenu.add_cascade(label="File",menu=m1)
m2=Menu(filemenu)

m2.add_command(label="cut",command=myfunc)
m2.add_command(label="copy",command=myfunc)
m2.add_separator()
m2.add_command(label="paste",command=myfunc)
m2.add_command(label="find",command=myfunc)
root.config(menu=filemenu)
filemenu.add_cascade(label="Edit",menu=m2)
root.mainloop()
